### ISSUE TITLE
리드미 예시 코드와 명세에 대한 질문입니다

### ISSUE THREAD

**Issue by ghost** [nunalang/nuna#6]
### 1

> 눈나..흐.....읏..나주..거....흐...읏... <-- 리드미 예시 코드 중 첫번째 줄

`흐~읏`에서 `읏` **뒤에** 점은 어떤 역할을 하나요?

### 2

> 누나..흐..읏나.......주..거......응읏..! <-- 리드미 예시 코드 중 네번째 줄

`읏`은 `흐~읏` 구문에서만 사용되는 것으로 보이는데 **맨 뒤에** `읏..`은 어떤 역할을 하나요?

### 3

> `으`은 앞의 스택의 값입니다. `.` 대신 사용 할 수 있습니다. <-- 명세 중에서

앞의 스택의 값입니다 라는 말이 이해되지 않습니다.
`나....` 등에서 `나으으으` 같이 쓸 수 있다는 말인가요?

### 4

> `응`는 현재 스택 앞의 내용과 현재 스택의 내용을 뺍니다 (현재 스택 앞의 스택은 삭제 됩니다) <-- 명세 중에서

현재 스택 앞의 내용에서 현재 스택의 내용을 뺴는 건지, 그 반대인지 알 수 없습니다.
명시할 필요가 있어보입니다.

### 추가: 5

> 눈나..으흐읏 <-- 리드미 예시 코드 중 다섯번째 줄

`흐`와 `읏` 사이에 점이 하나도 없습니다. 이 경우 2의 1 제곱으로 할지, 오류가 발생해야할지 알 수 없습니다.

**Comment by AkiaCode** [comment]
@pmh-only

**Comment by pmh-only** [comment]
@nkgcp

### 1
명세에 그와 관련된 조항이 없으므로 아무런 의미를 가지지 않고 아무 작업도 하지 않습니다.\
그 부분을 지우더라도 기능에는 아무런 문제가 없습니다.

### 2
1번과 같이 아무런 의미를 가지지 않습니다.

### 3
"앞 스택의 값"을 `.` 의 개수로 치환한다는것을 의미합니다.

예를 들어 1번 스택에는 3이 있고 현재 2번 스택을 가르키고 있다고 가정합시다.\
이 경우 `나으` 는 `나...`로 해석됩니다.\
비슷하게 `나....으`는 `나.......`으로 해석됩니다.

### 4
웹누나 구현체를 제작하며 저도 그 부분의 대하여 햇갈리는점이 많았습니다.\
추후 업데이트를 통해 해결하도록 하겠습니다.\
현재 공식 웹누나 구현체는 앞 내용에서 현 내용을 빼는것으로 구현되어 있습니다.

### 5
점이 없으므로 명세에 적힌 대로 `2의 1 제곱` 으로 해석합니다.

**Comment by pmh-only** [comment]
주말 안에 애매한 표현을 모두 해결할 v0.3.1을 배포할 예정입니다.\
관심 가져주셔서 감사합니다.
