### ISSUE TITLE
파일(.nuna) 구조 변경 요청

### ISSUE THREAD

**Issue by franknoh** [nunalang/nuna#9]
Nuna의 버전별로 문법이 조금씩 다릅니다.
실행할때마다 인터프리터, 코드의 호환성을 확인해야합니다.
.nuna 의 구조를 json 형식으로 할것을 요청합니다.

```json
{
  "version": "0.3",
  "script": "눈나..."
}
```

여기에 실행결과, 마지막 실행 시간등 다른 정보도
저장하면 좋을것같습니다.

**Comment by AkiaCode** [comment]
> Nuna의 버전별로 문법이 조금씩 다릅니다.
> 실행할때마다 인터프리터, 코드의 호환성을 확인해야합니다.
> .nuna 의 구조를 json 형식으로 할것을 요청합니다.
> 
> ```json
> {
>   "version": "0.3",
>   "script": "눈나..."
> }
> ```
> 
> 여기에 실행결과, 마지막 실행 시간등 다른 정보도
> 저장하면 좋을것같습니다.

 아니요, 그렇게 되면 그냥 .json 파일이랑  같기 떄문에 그렇게는 못하고 flag를 사용하면 될거 같습니다 ex) `nuna run -v3 *.nuna`

**Comment by franknoh** [comment]
그러면 코드와 인터프리터의 호환성을 어떻게 판별할까요?

**Comment by AkiaCode** [comment]
> 그러면 코드와 인터프리터의 호환성을 어떻게 판별할까요?

아까 전에 말했던 거 처럼 flag을 활용하시면 됩니다 ex) `nuna run -v3 *.nuna`
